spring.application.name=spring-boot
spring.datasource.url=jdbc:postgresql://localhost:5332/amigos
spring.datasource.username=amigoscode
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

resilience4j.circuitbreaker.instances.demoBreaker.sliding-window-size=5
resilience4j.circuitbreaker.instances.demoBreaker.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.demoBreaker.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.demoBreaker.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.demoBreaker.permitted-number-of-calls-in-half-open-state=2

management.endpoints.web.exposure.include=health,circuitbreakers,circuitbreakerevents
management.health.circuitbreakers.enabled=true

resilience4j.circuitbreaker.instances.flakyService.sliding-window-size=5
resilience4j.circuitbreaker.instances.flakyService.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.flakyService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.flakyService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.flakyService.permitted-number-of-calls-in-half-open-state=2